FROM python:3.12-slim AS builder
COPY --from=ghcr.io/astral-sh/uv:0.3.0 /uv /bin/uv
WORKDIR /app
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

FROM python:3.12-slim
WORKDIR /app
ENV PATH="/app/.venv/bin:$PATH"
COPY --from=builder /app/.venv /app/.venv
COPY src ./src
CMD ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "80"]
