import logging
from google.protobuf.struct_pb2 import Value
from google.protobuf.json_format import ParseDict
from a2a.server.agent_execution import AgentExecutor, RequestContext
from a2a.server.events import EventQueue
from a2a.types import (
    Task,
    TaskStatus,
    TaskState,
    TaskStatusUpdateEvent,
    TaskArtifactUpdateEvent,
    Artifact,
    Part
)
from app.core.rag import KairosRAGPipeline
from app.core.config import settings

logger = logging.getLogger(__name__)

class KairosAgentExecutor(AgentExecutor):
    """A2A AgentExecutor implementation for Kairos CDSS."""

    def __init__(self, pipeline: KairosRAGPipeline):
        self.pipeline = pipeline

    async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
        """Executes retrieval and synthesis for a clinical query."""
        task_id = context.task_id
        context_id = context.context_id
        
        logger.info(f"Starting execution of task {task_id} in context {context_id}")

        # 1. Update task state to WORKING
        await event_queue.enqueue_event(
            Task(
                id=task_id,
                context_id=context_id,
                status=TaskStatus(state=TaskState.TASK_STATE_WORKING)
            )
        )

        try:
            # 2. Extract clinical query text
            query = context.get_user_input()
            if not query.strip():
                raise ValueError("Clinical query input cannot be empty.")

            # 3. Retrieve context chunks from Qdrant
            logger.info(f"Retrieving clinical evidence for query: {query}")
            retrieved_chunks = await self.pipeline.retrieve(
                query=query, 
                top_k=settings.top_k
            )

            # 4. Synthesize clinical answer using Groq
            logger.info(f"Synthesizing clinical answer for task {task_id}")
            if not settings.groq_api_key:
                raise ValueError("GROQ_API_KEY environment variable is not configured.")
                
            answer_text = await self.pipeline.synthesize(
                query=query,
                chunks=retrieved_chunks,
                groq_api_key=settings.groq_api_key,
                model_name=settings.groq_model,
                temperature=settings.temperature
            )

            # 5. Enqueue Prose synthesized answer artifact
            answer_part = Part(text=answer_text, media_type="text/markdown")
            answer_artifact = Artifact(
                artifact_id=f"{task_id}_answer",
                name="Synthesized Clinical Answer",
                description="The clinical synthesis generated by Kairos based on retrieved PubMed literature.",
                parts=[answer_part]
            )
            await event_queue.enqueue_event(
                TaskArtifactUpdateEvent(
                    task_id=task_id,
                    context_id=context_id,
                    artifact=answer_artifact
                )
            )

            # 6. Enqueue Source citation metadata artifact
            sources_data = [
                {
                    "pmid": chunk.pmid,
                    "pmcid": chunk.pmcid,
                    "doi": chunk.doi,
                    "pubmed_url": chunk.pubmed_url,
                    "title": chunk.title,
                    "authors": chunk.authors,
                    "journal": chunk.journal,
                    "year": chunk.year,
                    "similarity_score": chunk.score,
                    "chunk_idx": chunk.chunk_idx
                }
                for chunk in retrieved_chunks
            ]
            sources_part = Part(
                data=ParseDict({"sources": sources_data}, Value()),
                media_type="application/json"
            )
            sources_artifact = Artifact(
                artifact_id=f"{task_id}_sources",
                name="Retrieved Evidence Sources",
                description="The structured citation metadata for the retrieved PubMed literature.",
                parts=[sources_part]
            )
            await event_queue.enqueue_event(
                TaskArtifactUpdateEvent(
                    task_id=task_id,
                    context_id=context_id,
                    artifact=sources_artifact
                )
            )

            # 7. Update task state to COMPLETED
            logger.info(f"Successfully completed execution of task {task_id}")
            await event_queue.enqueue_event(
                TaskStatusUpdateEvent(
                    task_id=task_id,
                    context_id=context_id,
                    status=TaskStatus(state=TaskState.TASK_STATE_COMPLETED)
                )
            )

        except Exception as e:
            logger.exception(f"Error executing A2A task {task_id}: {e}")
            await event_queue.enqueue_event(
                TaskStatusUpdateEvent(
                    task_id=task_id,
                    context_id=context_id,
                    status=TaskStatus(state=TaskState.TASK_STATE_FAILED)
                )
            )
            raise e

    async def cancel(self, context: RequestContext, event_queue: EventQueue) -> None:
        """Handles task cancellation request."""
        task_id = context.task_id
        context_id = context.context_id
        logger.warning(f"Task cancellation requested for task {task_id}")
        await event_queue.enqueue_event(
            TaskStatusUpdateEvent(
                task_id=task_id,
                context_id=context_id,
                status=TaskStatus(state=TaskState.TASK_STATE_CANCELED)
            )
        )
